version: '3'
services:

  gallery-is-db:
      image: "postgres:9.6-alpine"
      container_name: gallery-is-db
      volumes:
        - gallery-data:/var/lib/postgresql/data
      ports:
        - 5432:5432
      environment:
        - POSTGRES_DB=gallery
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin

  gallery-is-back:
      build: ./gallery-is-back
      container_name: gallery-is-back
      environment:
        - DB_SERVER=gallery-is-db
        - POSTGRES_DB=gallery
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
      ports:
        - 8080:8080
      links:
        - gallery-is-db

  gallery-is-front:
      build: ./gallery-is-front
      container_name: gallery-is-front
      ports:
        - 4200:80
      links:
        - gallery-is-back

volumes:
  gallery-data:



