version: "3.7"
services:

  festival-is-db:
    build: festival-is-db
    restart: always
    container_name: festival-is-db
    # TODO: long-time memory storage or init file
    #volumes:
    #  - festival-data:/var/lib/postgresql/data  
    networks:
      - backend-network
      
  festival-is-app:
    build: festival-is-app
    restart: always
    container_name: festival-is-app
    networks:
      - backend-network
      - frontend-network

  festival-is-web:
    build: festival-is-web
    restart: always
    container_name: festival-is-web
    ports:
      - 80:80
    networks:
      - frontend-network

# TODO: long-time memory storage or init file
#volumes:
#  festival-data:
networks:
  backend-network:
  frontend-network:
