DROP TABLE IF EXISTS Performance;
DROP TABLE IF EXISTS Festival ;
DROP TABLE IF EXISTS Stage ;
DROP TABLE IF EXISTS Band ;
DROP TABLE IF EXISTS Ticket ;


CREATE TABLE Performance(
    perf_id NUMBER(4) NOT NULL CONSTRAINT PK_PERFORMANCE PRIMARY KEY,
    fk_fest_id NUMBER(4) NOT NULL,
    fk_stage_id NUMBER(4) NOT NULL,
    fk_band_name NUMBER(4) NOT NULL,


    CONSTRAINT FK_FESTIVAL FOREIGN KEY (fk_fest_id) REFERENCES Festival(fest_id),
    CONSTRAINT FK_STAGE FOREIGN KEY (fk_stage_id) REFERENCES Stage(stage_id),
    CONSTRAINT FK_BAND FOREIGN KEY (fk_band_id) REFERENCES Band(band_id),
);

CREATE TABLE Festival (
    fest_id NUMBER(4) NOT NULL CONSTRAINT PK_FESTIVAL PRIMARY KEY,
    
)
 
CREATE TABLE Stage(
    stage_id NUMBER(4) NOT NULL CONSTRAINT PK_STAGE PRIMARY KEY,
)

CREATE TABLE Band (
    band_id NUMBER(4) NOT NULL CONSTRAINT PK_BAND PRIMARY KEY,
)

CREATE TABLE Ticket (
    ticket_id NUMBER(10) NOT NULL CONSTRAINT PK_TICKET PRIMARY KEY,
)

CREATE TABLE User (

)